{
    "import_path": "/data2/yufenggu/inference_results_v1.1/closed/Intel/code/resnet50/pytorch-cpu/",
    "backend-params": {
        "model_path": "/data2/yufenggu/inference_results_v1.1/closed/Intel/code/resnet50/data/",
        "ipex": "True",
        "dnnl": "True",
        "jit": "True",
        "configure_dir": "/data2/yufenggu/inference_results_v1.1/closed/Intel/code/resnet50/pytorch-cpu/resnet50_configure_jit_intel.json"
    },

    "dataset-params": {
        "data_path": "/data2/yufenggu/inference_results_v1.1/closed/Intel/code/resnet50/data/ILSVRC2012/",
        "image_list": "/data2/yufenggu/inference_results_v1.1/closed/Intel/code/resnet50/data/val_map.txt",
        "total_sample_count": 1024
    },
    
    "enqueue-params": {
        "batch_size": 128
    }

}
